const STATUS_CODE_POST = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_ON_SERVER = 500;

module.exports = {
  STATUS_CODE_POST, ERROR_BAD_REQUEST, ERROR_NOT_FOUND, ERROR_ON_SERVER,
};
